filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_docker_metadata: ~


setup.template.overwrite: true

setup.kibana.host: "https://kibana:5601/kibana"
setup.kibana.ssl.enabled: true
setup.kibana.ssl.certificate_authorities: "/usr/share/certificates/ca/ca.crt"
setup.kibana.ssl.certificate: "/usr/share/certificates/kibana/kibana.crt"
setup.kibana.ssl.key: "/usr/share/certificates/kibana/kibana.key"

setup.dashboards.enabled: true


output.elasticsearch:
  hosts: ["https://es01:9200","https://es02:9200","https://es03:9200"]
  username: "elastic"
  password: "changeme"
  ssl.certificate_authorities: "/usr/share/certificates/ca/ca.crt"
  ssl.certificate: "/usr/share/certificates/filebeat/filebeat.crt"
  ssl.key: "/usr/share/certificates/filebeat/filebeat.key"
