auditbeat.modules:

- module: auditd
  audit_rules: |
    -w /etc/passwd -p wa -k identity
    -a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -k access
    -a always,exit -S execve,execveat

- module: file_integrity
  paths:
    - /bin
    - /usr/bin
    - /sbin
    - /usr/sbin
    - /etc

- module: system
  datasets:
    - host
    - login
    - package
    - process
    - socket
    - user
  period: 10s
  state.period: 12h
  socket.include_localhost: false
  user.detect_password_changes: true

processors:
  - add_docker_metadata: ~


setup.template.overwrite: true

setup.kibana.host: "https://kibana:5601/kibana"
setup.kibana.ssl.enabled: true
setup.kibana.ssl.certificate_authorities: "/usr/share/certificates/ca/ca.crt"
setup.kibana.ssl.certificate: "/usr/share/certificates/kibana/kibana.crt"
setup.kibana.ssl.key: "/usr/share/certificates/kibana/kibana.key"
setup.ilm.enabled: false
setup.dashboards.enabled: true

monitoring:
  enabled: true
  elasticsearch:
    hosts: ["https://es01:9200","https://es02:9200","https://es03:9200"]
    username: "elastic"
    password: "changeme"

output.elasticsearch:
  hosts: ["https://es01:9200","https://es02:9200","https://es03:9200"]
  username: "elastic"
  password: "changeme"
  ssl.certificate_authorities: "/usr/share/certificates/ca/ca.crt"
  ssl.certificate: "/usr/share/certificates/auditbeat/auditbeat.crt"
  ssl.key: "/usr/share/certificates/auditbeat/auditbeat.key"

