[tls]
[[tls.certificates]]
  certFile = "/etc/ssl/traefik/server.crt"
  keyFile = "/etc/ssl/traefik/server.key"
  stores = ["default"]


[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/etc/ssl/traefik/server.crt"
      keyFile = "/etc/ssl/traefik/server.key"

