http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: ["https://es01:9200","https://es02:9200","https://es03:9200"]
xpack.monitoring.elasticsearch.username: "elastic"
xpack.monitoring.elasticsearch.password: "changeme" 
xpack.monitoring.elasticsearch.ssl.certificate_authority: /usr/share/certificates/ca/ca.crt
xpack.monitoring.enabled: true
pipeline.ecs_compatibility: "v1"
